### ISSUE TITLE
Wrong Java version identification for coretto/temurin-11.0.14.1 throws error

### ISSUE THREAD

**Issue by felix-mu** [tum-gis/rtron#11]
https://github.com/tum-gis/rtron/blob/5d7013f8d0e0b65418c0256211d39dc28b71d019/rtron-main/src/main/kotlin/io/rtron/main/system/JavaVersion.kt#L50-L59

https://github.com/tum-gis/rtron/blob/5d7013f8d0e0b65418c0256211d39dc28b71d019/rtron-main/src/main/kotlin/io/rtron/main/project/ProjectDSL.kt#L97-L100

**Comment by benediktschwab** [comment]
Thank you for reporting. Just fixed it for next release.
