### ISSUE TITLE
Missing prefix "#" in XLinks/hrefs

### ISSUE THREAD

**Issue by Son-HNguyen** [tum-gis/rtron#16]
The `href` attributes should have a prefix `#` in their value. 

Example:

+ Currently:

    ```xml
    <tran:successor xlink:href="id1"/>
    <tran:predecessor xlink:href="id2"/>
    ```

+ Should be:

    ```xml
    <tran:successor xlink:href="#id1"/>
    <tran:predecessor xlink:href="#id2"/>
    ```

**Comment by benediktschwab** [comment]
Thanks for reporting!
Was fixed by https://github.com/tum-gis/rtron/commit/4e2f2b121fe83ce907bc4fb21f930a9b3a7e3569.
