### ISSUE TITLE
Extracting Lane Markings from OpenDRIVE to CityGML

### ISSUE THREAD

**Issue by karanfc** [tum-gis/rtron#18]

**Comment by benediktschwab** [comment]
Lane marking export works for CityGML3.

**Comment by benediktschwab** [comment]
As this feature was also requested for CityGML2 in #20, I implemented it in https://github.com/tum-gis/rtron/commit/fe43ed1e5999b8cbcf61a3dfb24a6d7f7aa8bef3.
