### ISSUE TITLE
support OpenDRIVE header offset

### ISSUE THREAD

**Issue by benediktschwab** [tum-gis/rtron#19]
The offset values set in the OpenDRIVE header should be considered when transforming to CityGML.

**Comment by aminissn** [comment]
Just one small note: the projection string coming from the current version of SUMO misses one element, namely "+type=crs"  which is currently missing in the generated OpenDrive file. This should, however, be fixed in the next SUMO release. 
(see [#12288](https://github.com/eclipse/sumo/issues/12288) for details)

**Comment by benediktschwab** [comment]
Since f1347661, the offset values are considered starting from OpenDRIVE v.1.5 as this feature was introduced by ASAM for this version.
For a dataset of an earlier version, an offset can be added as an argument in the CLI.

@aminissn: Currently, rtron is not supporting geospatial coordinate reprojections, which could be handled by a library like [proj4j](https://github.com/locationtech/proj4j). It only resolves the offsets (either provided in the header or via CLI), and an [EPSG code](https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset) needs to be supplied to georeference the CityGML dataset (e.g.: `srsName="urn:ogc:def:crs:EPSG::25832"`). Once I tested to derive the EPSG code from the PROJ string (see [here](https://github.com/tum-gis/rtron/blob/94e85cc62dd5c30f7373bd9c120a588f2a60685f/rtron-math/src/test/kotlin/io/rtron/math/projection/CoordinateReferenceSystemTest.kt#L70-L86)), but the results were ambiguous and not satisfactory back then.
