### ISSUE TITLE
Correct predecessor and successor links according to driving direction

### ISSUE THREAD

**Issue by CodeMazeSolver** [tum-gis/rtron#28]
The CityGML linking of predecessor and successor elements is currently confusing, as it is dependent on the direction of the respective reference line used in OpenDRIVE. A correct linking regarding the driving direction should be considered.

**Comment by benediktschwab** [comment]
Well spotted and thanks for reporting! Should be fixed in [2428a0f](https://github.com/tum-gis/rtron/commit/2428a0f724ce767d4b1b5a92017c298b1f556bc6).
