### ISSUE TITLE
Fragmented connections for SIDEWALK and BIKING lanes

### ISSUE THREAD

**Issue by CodeMazeSolver** [tum-gis/rtron#33]
Currently, the output CityGML files are missing some successor and predecessor connections. As for the car lanes, the successor and predecessor connections seem to be working fine. However, the lane types `SIDEWALK` and `BIKING` suffer from some unset successor and predecessor connections which leads to fragmented networks of those lane types. This is especially significant in intersection areas where many `TrafficArea` and `TrafficSpace` objects exist to model the curved street. This can be seen in the following image, showing the `TrafficArea`s and their `TrafficSpace` (red) elements.

![image](https://github.com/tum-gis/rtron/assets/44395230/eaeef42e-9bda-4a22-a424-39259d280694)

There might be a way to set the right connections during the converting process. Otherwise, generating the missing connections using only the CityGML data  is a tedious task.

**Comment by benediktschwab** [comment]
Thanks for reporting. The question is whether the original OpenDRIVE dataset contains this connection information or not.
Can you provide me with the OpenDRIVE file and another enlarged screenshot to find this exact location?
You can send it to me via benedikt.schwab@tum.de.

**Comment by benediktschwab** [comment]
Thanks for providing the screenshot, @CodeMazeSolver. I double-checked and the `TrafficSpace`s shown in your image are missing a predecessor or successor relation because they are not connected in the OpenDRIVE dataset.
