### ISSUE TITLE
Missing UUIDs for `TrafficSpace` elements containing crosswalk and similar `TrafficArea`s

### ISSUE THREAD

**Issue by CodeMazeSolver** [tum-gis/rtron#34]
# Issue description

I noticed that within the generated CityGML file some `TrafficSpace` objects do not have an individual UUID. All of those occurrences seem to be related to the usage as a container for `TrafficArea` objects such as crosswalks.

For generating complete pedestrian networks  it could be beneficial to connect the two sides of the road via the `crossWalk` element by adding a usable `TrafficSpace` object and connecting it with predecessor and successor links to the `SIDEWALK` `TrafficSpace` objects next to the crosswalk.

The image shows a scene in which such a crosswalk is present in the output CityGML file. It has limited semantic information, compared to the other `TrafficArea`s of the road. Thus, it is just connected to the road via the generic attributes. 

![image](https://github.com/tum-gis/rtron/assets/44395230/29c28394-7e2a-44b2-a53c-6dac088d88ed)

# Code example
The following code shows the output CityGML data with the `TrafficSpace` elements missing a unique identifier (UUID).
```XML
<tran:trafficSpace>
    <tran:TrafficSpace>
        <boundary>
            <tran:TrafficArea gml:id="UUID_4b3f2da5-6f01-3393-aa26-58afc3faa71c">
                <gml:name>crossWalk</gml:name>
                    <genericAttribute>
                        <gen:StringAttribute>
                            <gen:name>identifier_roadObjectId</gen:name>
                            <gen:value>4030022</gen:value>
                       </gen:StringAttribute>
                    </genericAttribute>
                      ...
            </tran:TrafficArea>
        </boundary>
        <tran:granularity>lane</tran:granularity>
    </tran:TrafficSpace>
</tran:trafficSpace>
```

**Comment by benediktschwab** [comment]
Thanks for reporting! Yes, all `TrafficSpace`s and `TrafficArea`s need a GML ID. I'm currently fixing that.

Generally, `TrafficSpace`s and `TrafficArea`s  originate either from the [OpenDRIVE lanes](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-f9c6667b-7cf0-475b-bd90-4931b7b8142b) (containing lane predecessor/successor information) or from the [OpenDRIVE roadside objects](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-e12007a5-2961-4fa0-9de7-cf748a4f26ab). The latter does not contain any predecessor/successor information in the OpenDRIVE dataset and can be recognized by the existence of the generic attribute `identifier_roadObjectId` in the CityGML dataset. If you need them represented in the routing graph, you would probably have to perform geometric analyses to identify the (closest) adjacent sidewalks.

But this issue only addresses the missing GML IDs, right?

**Comment by CodeMazeSolver** [comment]
Yes, this is referring to the missing GML IDs.

For my application an available successor/predecessor connection would have been great. However, as they do not even exist in the OpenDRIVE dataset I would proceed and generate them by using the geometry to find adjacent sidewalks.

**Comment by benediktschwab** [comment]
Missing GML IDs should be fixed with https://github.com/tum-gis/rtron/commit/b2c3e9fb721b93b63fd589a9459d8c9ee96f24f1 on the develop branch.
