### ISSUE TITLE
relatedTo linking contains several links to the same CityFurniture element for TrafficSpace elements

### ISSUE THREAD

**Issue by CodeMazeSolver** [tum-gis/rtron#36]
The following TrafficSpace element (highlighted in green) is close to multiple CityFurniture elments. However, instead of having a link to the different CityFurniture elements it has several links to the same CityFurniture element with variables changing the corresponding lanes. I guess it should be the other way around that the CityFurniture object is connected to the different lanes present near the object.

![image](https://github.com/tum-gis/rtron/assets/44395230/16f59e3f-4dd5-4578-b14b-a406c61a9b3b)

The lane id for the selected TrafficSpace element is -4. The section id is constant for all referenced elements at 5.

![image](https://github.com/tum-gis/rtron/assets/44395230/159fc43b-e5e0-45cc-8452-491fd5062319)

![image](https://github.com/tum-gis/rtron/assets/44395230/3f1d1dc6-5d0f-4cbe-b742-ee97fbc4b47a)

The following screenshot shows the CityFurniture object that is referenced multiple times.

![image](https://github.com/tum-gis/rtron/assets/44395230/e7d03dbd-bfb8-43cd-9bdd-89a447dd23ca)

It contains links to multiple different TrafficSpace and AuxiliaryTrafficSpace objects.
 
![image](https://github.com/tum-gis/rtron/assets/44395230/924ae8b2-1e5f-4da4-9f5d-66a0afd23593)

This example is found in the Grafing dataset near the main square in the east. However, it is not the only occurrence of this issue.

**Comment by benediktschwab** [comment]
Thank you for reporting! This was a bug and should be fixed now. Please double-check with the new dataset I'm about to send you.
